"""
compare_agents.py — Agent Evaluation & Comparison
=================================================
Evaluates all four pricing agents over 100 episodes each and prints
a summary of average revenue.

Week 1: FixedPriceAgent, DiscountAgent  (baseline_agents.py)
Week 2: QLearningAgent                 (src/q_learning.py)
Week 3: DQNAgent                       (src/dqn_agent.py)

Run from the project root:
    python compare_agents.py

Pre-requisites:
    q_table.pkl        — generated by src/train_qlearning.py
    results/dqn_weights.pth — generated by src/train_dqn.py
"""

import pickle

from src.environment import DynamicPricingEnv
from baseline_agents import FixedPriceAgent, DiscountAgent
from src.q_learning import QLearningAgent
from src.dqn_agent import DQNAgent


def evaluate_agent(agent, env, episodes=100):

    revenues = []

    for _ in range(episodes):

        state, _ = env.reset()
        done = False
        total_reward = 0

        while not done:

            action = agent.choose_action(state)

            next_state, reward, done, _, _ = env.step(action)

            state = next_state
            total_reward += reward

        revenues.append(total_reward)

    return sum(revenues) / len(revenues)


env = DynamicPricingEnv()

# Fixed Agent
fixed_agent = FixedPriceAgent()
fixed_avg = evaluate_agent(fixed_agent, env)

# Discount Agent
discount_agent = DiscountAgent()
discount_avg = evaluate_agent(discount_agent, env)

# Q-Learning Agent
q_agent = QLearningAgent(num_actions=env.action_space.n)

with open("q_table.pkl", "rb") as f:
    q_agent.q_table.update(pickle.load(f))

q_agent.epsilon = 0

q_avg = evaluate_agent(q_agent, env)

# DQN Agent
# load() restores policy-net weights and syncs the target net internally.
dqn_agent = DQNAgent(
    state_dim=env.observation_space.shape[0],
    num_actions=env.action_space.n,
)

dqn_agent.load("results/dqn_weights.pth")
dqn_agent.epsilon = 0   # pure greedy — no exploration during evaluation

dqn_avg = evaluate_agent(dqn_agent, env)

print(f"Fixed Agent Avg Revenue:    {fixed_avg:.2f}")
print(f"Discount Agent Avg Revenue: {discount_avg:.2f}")
print(f"Q-Learning Avg Revenue:     {q_avg:.2f}")
print(f"DQN Agent Avg Revenue:      {dqn_avg:.2f}")